<!DOCTYPE html>
<html>

<head>
    <title></title>
    <?php require("include/meta.phtml"); ?>
</head>

<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <nav class="navbar navbar-expand-lg navbar-light bg-light">
                    <a class="navbar-brand" href="index.php">UDPT</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav mr-auto">
                            <?php
                            if (isset($_SESSION['user'])) {
                                echo "<li class='nav-item'><a class='nav-link' href='index.php?action=XemDanhSachDatHang'>Xem Danh Sach Dat Hang</a></li>";
                            } else {
                                echo "<li class='nav-item'><a class='nav-link' href='index.php?action=DatDichVu'>Đặt Dịch Vụ</a></li>
                                <li class='nav-item'><a class='nav-link' href='index.php?action=XemVaCapNhapDonHang'>Xem và Cập nhập đơn hàng</a></li>";
                            }
                            ?>
                        </ul>
                        <ul class="navbar-nav">
                            <?php
                            if (isset($_SESSION['user'])) {
                                echo "<li class='nav-item'><a class='nav-link' href='index.php?action=DangXuat'>Đăng Xuất</a></li>";
                            } else {
                                echo "<li class='nav-item'><a class='nav-link' href='index.php?action=DangNhap'>Đăng Nhập</a></li>";
                            }
                            ?>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
        <div class="row">
            <?php require($VIEW); ?>
        </div>
        <div class="row">
            <div class="col">
                FOOTER
            </div>
        </div>
    </div>
    </div>
</body>

</html>