<div class="col-12 mt-4">
    <form method="POST">
        <input type="hidden" name="action" value="DangNhap">
        <div class="form-group">
            <label for="exampleInputEmail1">Tài Khoản:</label>
            <input type="text" name="TenTK" class="form-control" id="exampleInputEmail1" placeholder="Nhập tài khoản">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">Mật Khẩu:</label>
            <input type="password" name="MatKhau" class="form-control" id="exampleInputPassword1" placeholder="Nhập mật khẩu">
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Đăng nhập</button>
        </div>
        <div class="form-group">
            <?php if ($message) {
                echo "<p class='mt-4'>{$message}</p>";
            } ?>
        </div>
    </form>
</div>