<div class="col-sm-12 mt-4">
    <div class="card">
        <h4 class="card-header">
            Nhập thông tin tra cứu
        </h4>
        <div class="card-body">
            <form method="POST">
                <input type="hidden" name="action" value="XemVaCapNhapDonHang">
                <div class="form-group">
                    <label for="txtMKH">Nhập Mã Khách Hàng:</label>
                    <input type="text" name="MaKH" class="form-control" id="txtMKH" autofocus require>
                </div>
                <button type="submit" class="btn btn-primary">
                    <i class="fa fa-check" aria-hidden="true"></i>
                    Tra Cứu
                </button>
                <div class="form-group">
                    <?php if ($message) {
                        echo "<p class='mt-4'>{$message}</p>";
                    } ?>
                </div>
            </form>
        </div>
    </div>
</div>